### ISSUE TITLE
Challenge6-2 margins for TileView are not applied on iOS 10.3.3

### ISSUE THREAD

**Issue by azhabort** [kharrison/albookcode#2]
Layout margins of 25px for TileView are not applied on the first app start on iOS 10.3.3. But after rotation correct margins are applied. Check screenshot:
![6-2 margins](https://user-images.githubusercontent.com/6636754/50479790-5e8f7280-09e9-11e9-8794-8bfa3bffb849.png)

**Comment by kharrison** [comment]
This seems to be a bug in iOS 10.x that was fixed in iOS 11. As far as I can tell it only seems to be a problem when adding the margin in a storyboard. Changing the margin in code does not seem to produce the same problem.

I've updated the latest version (should be released in the next week) of the book with a note on the issue. I can see two possible workarounds when hitting this issue:

1. set the layout margin in code
2. selecting "Preserve Superview Margins" on the subview in the storyboard seems to be sufficient to cause the custom margin to be applied when loading the view.

If you have come across a better solution let me know.
